Analysis: 
  Recording:
    species_presence_threshold: 0.03
    min_conf: 0.25
    file_check_poll_interval: 1
    lat: 42.5
    lon: -76.45
    date: 24/01/2024
  Model:
    sigmoid_sensitivity: 1.0
    num_threads: 2
    species_list_file: null

  SpeciesPresence: 
    threshold: 0.03
    num_threads: 1
    use_cache: true

  modelname: birdnet_default
  pattern: ".wav"
  check_time: 1
  delete_recordings: "never"
  model_dir: ~/iSparrow/models 

Data: 
  input: ~/iSparrow_data
  output: ~/iSparrow_output
  Preprocessor:
    sample_rate: 48000
    overlap: 0.0
    sample_secs: 3.0
    resample_type: kaiser_fast