version: '3'
services:
  faunanet:
    build: 
      context: .
      args:
        INSTALL_OPTION: ${tensorflow_version}
    volumes:
      - ~/faunanet_data:/home/faunanet/faunanet_data
      - ~/faunanet_output:/home/faunanet/faunanet_output
      - ~/faunanet_config:/home/faunanet/faunanet_config

  faunanet_record:
    image: faunanet_record:latest
    volumes:
      - ./faunanet_data:/home/faunanet/faunanet_data
      - ./faunanet_config:/home/faunanet/faunanet_config
    devices:
      - /dev/snd:/dev/snd # TODO: this needs to be the microphone device

  faunanet_chirp: # TODO: This does not yet exist
    image: faunanet_chirp:latest
    volumes:
      - ./faunanet_output:/home/faunanet/faunanet_output
      - ./faunanet_config:/home/faunanet/faunanet_config
    devices:
      - /dev/snd:/dev/snd #TODO: GPRS THING