Analysis:
  Model:
    model_name: birdnet_custom
    default_model_path: birdnet_default
    sigmoid_sensitivity: 1.0
    num_threads: 1

  Recording:
    species_presence_threshold: 0.03
    min_conf: 0.1
