Analysis:
  Watcher:
    output: ~/iSparrow_output
    input: &datafolder ~/iSparrow_data
    pattern: ".wav"
    check_time: 1
    delete_recordings: "on_cleanup"

  Preprocessor:
    sample_rate: 48000
    overlap: 0.0
    sample_secs: 3.0
    resample_type: "kaiser_fast"

  Model:
    model_name: birdnet_default
    sigmoid_sensitivity: 1.0
    num_threads: 1

  Recording:
    # lat: 42.5
    # lon: -76.45
    # date: 24-01-2024 #format: dd-mm-yyyy, "%Y-%m-%d"
    date: null
    lat: null
    lon: null
    species_presence_threshold: 0.03
    min_conf: 0.25
    species_predictor: null
    file_check_poll_interval: 1

  SpeciesPredictor:
    num_threads: 1
    use_cache: true
