Analysis:
  Watcher:
    output: ~/iSparrow_output
    input: &datafolder ~/iSparrow_data
    pattern: ".wav"
    check_time: 1
    delete_recording: "on_cleanup"

  Preprocessor: 
    sample_rate: 48000
    overlap: 0.0
    sample_secs: 3.0
    resample_type: "kaiser_fast"

  Model:
    default_model_path: None # only used for custom classifiers
    model_name: birdnet_default
    sigmoid_sensitivity: 1.0
    num_threads: 1

  Recording: 
    latitude: 42.5
    longitude: -76.45
    date: 24-01-2024 #format: dd-mm-yyyy, "%Y-%m-%d"
    threshold: 0.03
    min_conf: 0.25

  SpeciesPredictor: 
    num_threads: 1
    use_cache: true

Data: 
  Collection: 
    output: *datafolder
    runtime: 9 # for security: 
    # run_until: 2024-04-04_12:05:24  # format: "%Y-%m-%d_%H:%M:%S"
    dump_config: True
    data_folder_suffix: ""
  Recorder:
    sample_rate: 48000
    length_s: 3
    channels: 1
    mode: "record"
