Analysis:
  Model:
    model_path: birdnet_default
    sigmoid_sensitivity: 1.0
    num_threads: 12

  SpeciesPresence:
    latitude: 42.5
    longitude: -76.45
    week: 4
    date: 24/01/2024
    threshold: 0.03
    num_threads: 2
    use_cache: true

  min_conf: 0.25
  use_species_presence_model: true

Data:
  Results: 
    result_folder: ~/iSparrow/results
    write_every: 100
  Output:
    output_folder: ~/iSparrow/data
    runtime: 9 # for security: run with default should not run forever
    # run_until: 2024-04-04_12:05:24  # format: "%Y-%m-%d_%H:%M:%S"
    dump_config: True
    data_folder_suffix: ""
  Recording:
    sample_rate: 48000
    length_s: 3
    channels: 1
    mode: "record"
  Preprocessor:
    sample_rate: 48000
    overlap: 0.0
    sample_secs: 3.0
    resample_type: kaiser_fast
