services:
  faunanet:
    image: mahawo/faunanet_tf:latest # put in the image name of the container you want to use
    tty: true 
    stdin_open: true
    volumes:
      - ~/faunanet_output:/root/faunanet_output
      - ~/faunanet/models:/root/faunanet/models
      - faunanet_data:/root/faunanet_data
    environment:
      - RUN_CONFIG=config.yml
  faunanet_record:
    image: mahawo/faunanet_record:latest
    tty: true 
    volumes: 
      - faunanet_data:/root/faunanet_data
    devices:
      - /dev/snd:/dev/snd # this needs to be the microphone device
    environment:
      - RUN_CONFIG=config.yml
volumes:
  faunanet_data:
    driver: overlay2