services:
  faunanet:
    image: mahawo/faunanet:latest
    tty: true 
    stdin_open: true
    volumes:
      - ~/faunanet_config:/root/faunanet_config
      - ~/faunanet_output:/root/faunanet_output
      - ~/faunanet/models:/root/faunanet/models
      - ~/faunanet_data:/root/faunanet_data
    # environment:
    #   - RUN_CONFIG=config.yml
  faunanet_record:
    image: mahawo/faunanet_record:latest
    tty: true 
    stdin_open: true
    volumes:
      - ~/faunanet_config:/root/faunanet_config
      - ~/faunanet_data:/root/faunanet_data
    devices:
      - /dev/snd:/dev/snd # this needs to be the microphone device
    # environment:
    #   - RUN_CONFIG=config.yml