services:
  faunanet:
    image: mahawo/faunanet_tf:latest # put in the image name of the container you want to use
    tty: true 
    stdin_open: true
    volumes:
      - ~/faunanet/output:/home/faunanet/output
      - ~/faunanet/models:/home/faunanet/custom_models
      - ~/faunanet/config:/home/faunanet/config
      - ~/faunanet/data:/home/faunanet/data
    environment:
      - RUN_CONFIG=analysis.yml
  faunanet_record:
    image: mahawo/faunanet_record:latest
    tty: true
    stdin_open: true
    volumes: 
      - ~/faunanet/data:/home/faunanet/data
      - ~/faunanet/config:/home/faunanet/config
    devices:
      - /dev/snd:/dev/snd # this needs to be the microphone device
    environment:
      - RUN_CONFIG=record.yml
