# services:
#   faunanet:
#     image: mahawo/faunanet_tf:latest # put in the image name of the container you want to use
#     tty: true 
#     stdin_open: true
#     volumes:
#       - ~/faunanet/output:/root/faunanet_output
#       # - ~/faunanet/models:/root/faunanet/models
#       - ~/faunanet/config:/root/faunanet_config
#       - ~/faunanet/data:/root/faunanet_data
    # environment:
    #   - RUN_CONFIG=analysis.yml
    # user: "501:20"
#   faunanet_record:
#     image: mahawo/faunanet_record:latest
#     tty: true
#     stdin_open: true
#     volumes: 
#       - ~/faunanet/data:/root/faunanet_data
#       - ~/faunanet/config:/root/faunanet_config
#     devices:
#       - /dev/snd:/dev/snd # this needs to be the microphone device
#     environment:
#       - RUN_CONFIG=record.yml
# volumes:
#   faunanet_data: {}

services:
  faunanet:
    image: mahawo/faunanet_tf:latest
    tty: true 
    stdin_open: true
    volumes:
      - faunanet_output:/root/faunanet/output
      - faunanet_config:/root/faunanet/config
      - faunanet_data:/root/faunanet/data
      - faunanet_models:/root/faunanet/custom_models
    environment:
      - RUN_CONFIG=analysis.yml
  faunanet_record:
    image: mahawo/faunanet_record:latest
    tty: true
    stdin_open: true
    volumes: 
      - faunanet_data:/root/faunanet/data
      - faunanet_config:/root/faunanet/config
    devices:
      - /dev/snd:/dev/snd
    environment:
      - RUN_CONFIG=record.yml
volumes:
  faunanet_output:
  faunanet_config:
  faunanet_data:
  faunanet_models: